### ISSUE TITLE
Completion status

### ISSUE THREAD

**Issue by sleperf** [netspotau/moodle-mod_mediagallery#4]
If we set the activity completion to "Show activity as complete when conditions is met" and check "Student must view this activity to complete it" in the activity parameters, the activity is never set as completed for a strudent.

**Comment by aolley** [comment]
Hi @sleperf,

To help me narrow this down, could you let me know:
1) your moodle version
2) the version of the mediagallery plugin you're using.

Thanks!

**Comment by sleperf** [comment]
We are currently using Moodle 2.7 and the plugin version is 2015021103.

**Comment by aolley** [comment]
Hi @sleperf,

Completion tracking was fixed in the latest version. You can either update your copy of the plugin, or put these lines in the mod/mediagallery/view.php file after the $course and $cm objects are loaded:

require_once($CFG->libdir . '/completionlib.php');
$completion = new completion_info($course);
$completion->set_module_viewed($cm);
